name: Create artifact
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create artifact
        run: |
          mkdir -p artifact
          echo "Hello world" > artifact/hello.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello
          path: artifact